name: Keepalive

on:
  schedule:
    - cron: '0 0 */20 * *'
  workflow_dispatch:

permissions:
  contents: write        # ← 이 부분 추가

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
